package euler;
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
 */
public class P2_Fibonacci
{
	public static void main(String[] args)
	{
		int t1=1, t2=0; long total=0;
		while(true)
		{
			int next=t1+t2;
			System.out.println(next);
			if (next>4000000)
				break;
			if (next%2==0)
				total+=next;
			t1 = t2;
			t2 = next;
		}
		
		System.out.println ("Total = " + total);
	}
}
